server:
  port: 80

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.application.usedallea
  configuration:
    map-underscore-to-camel-case: true