spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/smms?serverTimeZone=Asia/Seoul?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy